services:
  postgres:
    container_name: postgres
    build: ./docker-files/database
    ports:
      - "5432:5432"
    volumes:
      - "./docker-files/database/init-files:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  node:
    container_name: node
    build: ./docker-files/node
    working_dir: /home/node/projects
    ports:
      - "3000:3000" # frontend
      - "3001:3001" # backend
    volumes:
      - node-data:/home/node/projects
    tty: true
    stdin_open: true

volumes:
  node-data:
